using System;

namespace knightmoves;

class Program
{
    static void Main(string[] args)
    {
        // Do not make changes to this File
        string[] phrases = {
            "A Momentary Lapse",
            "A Reflection Of Our Times",
            "A Cursory Glance",
            "A Dead Ringer",
            "A Far Far Better Thing",
            "A Figment Of Your Imagination",
            "A Fox In The Henhouse",
            "A Fresh Point Of View",
            "A Friend In Need Is A Friend Indeed",
            "A Gleam In Your Eye",
            "A Gutsy Move",
            "A Land-Office Business",
            "A Matter Of Policy",
            "A Meal In Itself",
            "A Moot Point",
            "A Novel Idea",
            "A Penny For Your Thoughts",
            "A Plan Of Action",
            "A Rolling Stone Gathers No Moss",
            "A Run For Your Money",
            "A Slight Chance Of Showers",
            "A Stab In The Back",
            "A Stitch In Time Saves Nine",
            "A Straw In The Wind",
            "A Sure Thing",
            "A Total Loss",
            "Alive And Kicking",
            "All Along The Line",
            "All That Glitters Is Not Gold",
            "All's Fair In Love And War",
            "An Apple A Day Keeps The Doctor Away",
            "An Exception To The Rule",
            "An Extra Pair Of Eyes",
            "An Uphill Battle",
            "And All That Jazz",
            "Animal Vegetable Or Mineral",
            "Are You Decent",
            "Are You Waiting For An Engraved Invitation",
            "Around The Bend",
            "As Pure As The Driven Snow",
            "As Rare As Hens' Teeth",
            "At Any Rate",
            "At The Helm",
            "At The Present Time",
            "At The Same Time",
            "Batteries Not Included",
            "Battling The Forces Of Evil",
            "Be Still",
            "Been Down So Long It Looks Like Up To Me",
            "Before The Parade Passes You By",
            "Beggars Can't Be Choosers",
            "Behave Yourself",
            "Behind The Scenes",
            "Behind The Eight-Ball",
            "Behind The Wheel",
            "Besieged With Requests",
            "Betwixt And Between",
            "Birds Of A Feather Flock Together",
            "Bite The Bullet",
            "Blood Is Thicker Than Water",
            "Brace Yourself",
            "Breath-Taking Beauty",
            "Bring Them Into The Fold",
            "Busy As A Bee",
            "Buying On Margin",
            "By The Nape Of The Neck",
            "Call A Cab",
            "Can A Leopard Change Its Spots",
            "Can I Quote You On That",
            "Cash And Carry",
            "Cash On The Barrelhead",
            "Cast Aspersions",
            "Catch-As-Catch-Can",
            "Caught Short-Handed",
            "Cease And Desist",
            "Change Your Tune",
            "Charity Begins At Home",
            "Check Please",
            "Check Your Sources",
            "Chewing Its Cud",
            "Class Dismissed",
            "Clean Your Room",
            "Clip Coupons",
            "Close Quarters",
            "Closed Until Further Notice",
            "Cross Your Palm With Silver",
            "Cry Yourself To Sleep",
            "Curiosity Killed The Cat",
            "Current Whereabouts Unknown",
            "Cut And Dried",
            "Cut And Paste",
            "Cute As A Button",
            "Dim The Lights",
            "Dinner Is In The Oven",
            "Do Your Duty",
            "Don't Look Back",
            "Don't Make Waves",
            "Don't Talk Back",
            "Don't Be So Naive",
            "Don't Be Such A Pest",
            "Don't Get Nasty With Me",
            "Don't Give Me Any Lip",
            "Don't Just Stand There",
            "Don't Let It Slip Away",
            "Don't Lie Down On The Job",
            "Don't Put All Your Eggs In One Basket",
            "Don't Stand On Ceremony",
            "Don't Take It Lying Down",
            "Double Your Pleasure",
            "Down The Drain",
            "Down Under",
            "Duck For Cover",
            "Earn Your Keep",
            "Easier Said Than Done",
            "East Is East And West Is West",
            "End Of The Line",
            "End Of The Road",
            "Enjoy It While You Can",
            "Enough Is Enough",
            "Every Cloud Has A Silver Lining",
            "Every Tom Dick And Harry",
            "Face To Face",
            "Facing The Future",
            "Fade Away",
            "Fair To Middling",
            "Faith And Trust",
            "Fame And Fortune",
            "Familiarity Breeds Contempt",
            "Famous Last Words",
            "Feed A Cold And Starve A Fever",
            "Feel The Heat",
            "Fifteen Minutes Of Fame",
            "Fighting Tooth And Nail",
            "Fill Me In On It",
            "Find Favor With",
            "Finders Keepers",
            "Fleet Of Foot",
            "Fluent In Five Languages",
            "Fly By Night",
            "Flying Blind",
            "Foiled At Every Turn",
            "Follow The Leader",
            "Follow The Herd",
            "Fool's Errand",
            "Foot The Bill",
            "Footloose And Fancy Free",
            "For Heaven's Sake",
            "For Pity's Sake",
            "For All Intents And Purposes",
            "For All The World To See",
            "For Better For Worse",
            "For Keeps",
            "For Richer For Poorer",
            "For The Love Of Mike",
            "For Your Information",
            "Fork It Over",
            "From Another Planet",
            "From Coast To Coast",
            "From Stem To Stern",
            "From This Day Forward",
            "Funny Money",
            "Game Set And Match",
            "Get A Grip On Yourself",
            "Get A Leg Up",
            "Get A Fix On It",
            "Get In Just Under The Wire",
            "Getting A Fair Shake",
            "Getting The Cold Shoulder",
            "Giant Size",
            "Give Him Enough Rope To Hang Himself",
            "Give Him His Walking Papers",
            "Give It The Old College Try",
            "Give It Your Best Effort",
            "Give Me A Sign",
            "Give Your Notice",
            "Glad To Meet You",
            "Go Ahead Sue Me",
            "Go Figure",
            "Go For Broke",
            "Go Out Of Your Way",
            "Going Full Throttle",
            "Going Going Gone",
            "Going Great Guns",
            "Going To Town",
            "Going By The Script",
            "Gone Fishin'",
            "Gone To Seed",
            "Good Grief",
            "Good For Nothing",
            "Graduate With Honors",
            "Great Day In The Morning",
            "Grow Up",
            "Guess Again",
            "Guilty As Charged",
            "Halt Who Goes There",
            "Hand Over Fist",
            "Hands Up",
            "Hang Around",
            "Hang On",
            "Hardly A Day Goes By",
            "Haste Makes Waste",
            "Have A Nice Day",
            "Haven't Seen Hide Nor Hair Of Him",
            "Having A Ball",
            "He Got A Raw Deal",
            "He Speaks Very Highly Of You",
            "He Who Hesitates Is Lost",
            "He's Got A Few Loose Screws",
            "Heaven And Earth",
            "Heaven Only Knows",
            "Heavens Above",
            "Here And Now",
            "High And Dry",
            "Highs And Lows",
            "His And Hers",
            "Hit The Jackpot",
            "Hold On Tight",
            "Holding Up Your End Of The Bargain",
            "Home Sweet Home",
            "How Much Do You Need",
            "Hurry Home",
            "I Beg Your Pardon",
            "I Can Manage Just Fine",
            "I Can't Recall",
            "I Demand My Rights",
            "I Don't Mind If I Do",
            "I Don't Want To Burst Your Bubble",
            "I Gave At The Office",
            "I Gave It Up For Lent",
            "I Hate To Eat And Run",
            "I Have No Use For It",
            "I Have Nothing More To Say",
            "I Have It All At My Fingertips",
            "I Haven't Got A Clue",
            "I Hear You Loud And Clear",
            "I Knew It All Along",
            "I Know What I Saw",
            "I Like It Like That",
            "I Mean What I Say",
            "I Regret To Inform You",
            "I Second The Motion",
            "I Spoke Too Soon",
            "I Tip My Hat To You",
            "I Want To Be Alone",
            "I Wash My Hands Of It",
            "I'll Be With You In A Minute",
            "I'll Run A Tab",
            "I'll Take You At Your Word",
            "I'm Looking Forward To It",
            "I'm Fond Of You",
            "I'm In Seventh Heaven",
            "I'm Not Buying It",
            "I'm Out Of Here",
            "I'm Stuck On You",
            "I'm Trying To Get The Kinks Out",
            "I've Formed An Opinion",
            "I've Got My Money On You",
            "If Looks Could Kill",
            "In Broad Daylight",
            "In Fits And Starts",
            "In Hot Water",
            "In My Neck Of The Woods",
            "In One Ear And Out The Other",
            "In The Face Of Danger",
            "In The Flesh",
            "In The Line Of Duty",
            "In The Nick Of Time",
            "In The Prime Of Life",
            "In Your Neck Of The Woods",
            "In Your Stocking Feet",
            "It Couldn't Happen To A Nicer Guy",
            "It Didn't Pan Out",
            "It Didn't Ring True",
            "It Never Fails",
            "It Seems Like Only Yesterday",
            "It Takes All Kinds",
            "It Takes Guts",
            "It Takes Two To Tango",
            "It Varies From Day To Day",
            "It Will Come To Pass",
            "It's A Crying Shame",
            "It's A Dog-Eat-Dog World",
            "It's A Living",
            "It's A Pity",
            "It's A Snap",
            "It's All The Rage",
            "It's High Time",
            "It's No Skin Off My Nose",
            "It's No Use Crying Over Spilt Milk",
            "It's Not All It's Cracked Up To Be",
            "It's Only Money",
            "It's Your Move",
            "Jumping To Conclusions",
            "Just Like Starting Over",
            "Just One Of The Guys",
            "Keep At It",
            "Keep It To Yourself",
            "Keep It Under Wraps",
            "Keep The Peace",
            "Keep Those Cards And Letters Coming",
            "Keep Time",
            "Keep Your Eyes Peeled",
            "Keep Your Fingers Crossed",
            "Keep Your Head",
            "Keep Your Losses To A Minimum",
            "Keeping Things On An Even Keel",
            "Keeping Up With The Joneses",
            "Knock On Wood",
            "Land On Your Feet",
            "Landed With A Thud",
            "Larger Than Life",
            "Last But Not Least",
            "Lean And Mean",
            "Less Is More",
            "Let It Ride",
            "Let The Buyer Beware",
            "Let Your Hair Down",
            "Let's Make Tracks",
            "Let's Play Fair",
            "Lie In State",
            "Like A Bull In A China Shop",
            "Like Father Like Son",
            "Like Taking Candy From A Baby",
            "Like Two Peas In A Pod",
            "Listen To Reason",
            "Living Proof",
            "Living Up To Expectations",
            "Living In The Lap Of Luxury",
            "Lo And Behold",
            "Loads Of Fun",
            "Look Before You Leap",
            "Looks Aren't Everything",
            "Lost And Found",
            "Made In America",
            "Make Yourself Scarce",
            "Make A Funny Face",
            "Make Me An Offer I Can't Resist",
            "Make Time",
            "Make Way",
            "Making A Big Splash",
            "Making Eye Contact",
            "Meeting On Neutral Ground",
            "Might Makes Right",
            "Mind Your Own Business",
            "Moving At A Snail's Pace",
            "My Suitcases Are Packed",
            "Neat As A Pin",
            "Never A Dull Moment",
            "Never Trust Anyone Over Thirty",
            "New And Improved",
            "News At Eleven",
            "Nice To See You",
            "No Offense Meant",
            "No Questions Asked",
            "No More Mr. Nice Guy",
            "No Place To Hide",
            "No Pun Intended",
            "No Room For Error",
            "No Takers",
            "Not At The Moment",
            "Not For All The Tea In China",
            "Not For Publication",
            "Not My Style",
            "Not On Your Life",
            "Not Worth A Hill Of Beans",
            "Nothing But Trouble",
            "Nothing But The Best",
            "Nothing In Common",
            "Nothing To Lose",
            "Now Hear This",
            "Nurse Your Wounds",
            "Odd Man Out",
            "Off Limits",
            "Off And Running",
            "Off To The Races",
            "Old Habits Die Hard",
            "On The Face Of It",
            "On The Launching Pad",
            "On The Level",
            "On The Make",
            "On The Right Track",
            "On The Straight And Narrow",
            "On The Tip Of My Tongue",
            "On The Verge Of Tears",
            "On The Move",
            "On The Run",
            "Once And For All",
            "Once In A Blue Moon",
            "One In A Million",
            "One Size Fits All",
            "Or So He Said",
            "Out Of Harm's Way",
            "Out Of Sync",
            "Out Of The Clear Blue Sky",
            "Out Of The Loop",
            "Out Of The Mouths Of Babes",
            "Out Of The Running",
            "Out Of Touch",
            "Out On My Own",
            "Over Hill And Dale",
            "Over The Edge",
            "Over The Top",
            "Over The Top",
            "Pacing Back And Forth",
            "Paid In Full",
            "Pamper Yourself",
            "Pancakes",
            "Paper Or Plastic",
            "Pay The Piper",
            "Pay Your Dues",
            "Pay Your Own Way",
            "People Will Talk",
            "Pick A Card Any Card",
            "Pick Up The Pace",
            "Pinching Pennies",
            "Pitch Black",
            "Places Everyone",
            "Places Everyone",
            "Playing By The Rules",
            "Please Wait Your Turn",
            "Poetic Justice",
            "Poetry In Motion",
            "Point Of No Return",
            "Power To The People",
            "Practice Makes Perfect",
            "Pretty As A Picture",
            "Pull Back On The Reins",
            "Pure Coincidence",
            "Pure As The Driven Snow",
            "Put Out The Fire",
            "Put Up A Good Fight",
            "Put Your Cards On The Table",
            "Putting Down Roots",
            "Quick As A Wink",
            "Quit While Yo're Ahead",
            "Ragged Around The Edges",
            "Rags To Riches Story",
            "Raining Cats And Dogs",
            "Ran Into A Little Snag",
            "Ranting And Raving",
            "Reaching The Outer Limits",
            "Recommended Dosage",
            "Related On My Mother's Side",
            "Remember When",
            "Ride Herd",
            "Riding Tall In The Saddle",
            "Right Of Way",
            "Ring Around The Rosie",
            "Rinky-Dink",
            "Roll The Dice",
            "Roll Up Your Sleeves",
            "Room For One More",
            "Rough Sailing Ahead",
            "Round Off To The Nearest Number",
            "Ruffled Feathers",
            "Run For Your Life",
            "Run Of The Mill",
            "Safe And Sound",
            "Sail Away",
            "Save Your Pennies For A Rainy Day",
            "Say Uncle",
            "Scared Stiff",
            "Season's Greetings",
            "Seize The Moment",
            "Selling Like Hotcakes",
            "Sent Him Packing",
            "Served On A Silver Platter",
            "Set Aside Some Time",
            "Set In His Ways",
            "Share And Share Alike",
            "Ship Ahoy",
            "Short-Changed",
            "Sight Unseen",
            "Sign Of The Times",
            "Signed Sealed And Delivered",
            "Sincerely Yours",
            "Sit Back And Relax",
            "Skating On Thin Ice",
            "Skin Deep",
            "Slim Pickings",
            "Slip Of The Tongue",
            "Smooth As Silk",
            "Snake Eyes",
            "Snuggle Up",
            "Sole Support",
            "Something To That Effect",
            "Soon Enough",
            "Sound The Wrong Note",
            "Spare The Rod And Spoil The Child",
            "Speak Of The Devil",
            "Spring Fever",
            "Stand Back And Watch The Fur Fly",
            "Stand Pat",
            "State Of The Art",
            "Stay On Your Toes",
            "Stay Tuned",
            "Steal Away",
            "Stem The Tide",
            "Stick It Out",
            "Stick Out Your Tongue",
            "Stir It Up",
            "Stop At Nothing",
            "Stop Making A Scene",
            "Store This End Up",
            "Stow Your Gear Here",
            "Street Smart",
            "Strictly Business",
            "Strike While The Iron Is Hot",
            "Strike A Pose",
            "Strike It Rich",
            "Supply And Demand",
            "Swan Song",
            "Sweep Under The Rug",
            "Sweet Dreams",
            "Swing Shift",
            "Take A Memo",
            "Take After Meals",
            "Take Detailed Notes",
            "Take Heart",
            "Take Your Pick",
            "Take A Back Seat",
            "Take A Load Off",
            "Take A Peek",
            "Take A Siesta",
            "Take It Easy",
            "Take It On The Chin",
            "Take It With A Grain Of Salt",
            "Taken By Storm",
            "Taking Advantage Of The Situation",
            "Taking Care Of Business",
            "Taking The Lion's Share",
            "Taking Turns",
            "Taking A Nap",
            "Talk A Blue Streak",
            "Talk It Over",
            "Thank Your Lucky Stars",
            "That Really Hits Home",
            "That Remains To Be Seen",
            "That Hits The Spot",
            "That Was Then This Is Now",
            "That'll Do The Trick",
            "That's Strong Medicine",
            "That's Tooting Your Own Horn",
            "That's All She Wrote",
            "That's All Well And Good",
            "That's Not The Worst Of It",
            "That's The Way Of The World",
            "The Bigger They Are The Harder They Fall",
            "The Calm Before The Storm",
            "The Check Is In The Mail",
            "The Crux Of The Matter",
            "The Day Before Yesterday",
            "The Early Bird Catches The Worm",
            "The Facts Of Life",
            "The Hustle And Bustle Of The Big City",
            "The Lay Of The Land",
            "The Letter Of The Law",
            "The Manner To Which You Are Accustomed",
            "The Milk Of Human Kindness",
            "The More The Merrier",
            "The Pen Is Mightier Than The Sword",
            "The Plot Thickens",
            "The Pot Calling The Kettle Black",
            "The Proof Is In The Pudding",
            "The Sky's The Limit",
            "The Talk Of The Town",
            "The Thrill Is Gone",
            "The Voice Of Reason",
            "The Whole Kit And Caboodle",
            "The Whole Truth And Nothing But The Truth",
            "The Worst Is Over",
            "There's No Time Like The Present",
            "There's No Such Thing As A Free Lunch",
            "Thick As Thieves",
            "Things Are Looking Up",
            "Things Are Tough All Over",
            "Things Change",
            "Third Time's A Charm",
            "Throw In The Towel",
            "Tighten The Purse Strings",
            "Time And A Half",
            "Timing Is Everything",
            "Tip The Scales",
            "To Say The Least",
            "To Your Health",
            "Together In Unison",
            "Too Many Cooks Spoil The Broth",
            "Torn In Half",
            "Transfer Of Deed",
            "Trial And Error",
            "True Blue",
            "Tune It Out",
            "Turned It Down Flat",
            "Turned Tail And Ran",
            "Twenty-Twenty Hindsight",
            "Twice As Nice",
            "Two Of A Kind",
            "Two Wrongs Don't Make A Right",
            "Until Further Notice",
            "Up To The Minute",
            "User-Friendly",
            "Vice Versa",
            "Wait Till Your Father Gets Home",
            "Walk Down The Aisle",
            "Walk The Plank",
            "Wandering Around In A Complete Fog",
            "Watch Out",
            "We're Going Places",
            "We're Poles Apart",
            "We're In The Money",
            "Westward Ho",
            "What A Good Idea",
            "What Do You Make Of That",
            "What Exactly Are You Trying To Say",
            "What's Mine Is Yours",
            "What's The Score",
            "What's Done Is Done",
            "When I Say Jump You Ask How High",
            "When Push Comes To Shove",
            "Where There's A Will There's A Way",
            "Where There's Smoke There's Fire",
            "Wherever You May Roam",
            "Whet Your Appetite",
            "Why Not",
            "Why The Long Face",
            "Win By A Nose",
            "Win Place Or Show",
            "Wipe Out",
            "Wishes Do Come True",
            "With A Little Luck",
            "Within Reason",
            "Without A Trace",
            "Woe Is Me",
            "Won't You Please Join Us",
            "Working Nine To Five",
            "Worth His Weight In Gold",
            "Write It Off",
            "Year In Year Out",
            "You Are Cordially Invited",
            "You Can Take My Place",
            "You Can't Have Your Cake And Eat It Too",
            "You Can't Make A Silk Purse Out Of A Sow's Ear",
            "You Can't Teach An Old Dog New Tricks",
            "Yo'll Have Your Say",
            "Yo're A Saint",
            "Yo're Not My Cup Of Tea",
            "Young At Heart",
            "Your Number's Up",
            "Your Place Or Mine",
            "Yours Truly"};

        int max = phrases.Length - 1;
        int phraseIndex = new Random().Next(0, max);

        string phrase = phrases[phraseIndex];
        var game = new Game(phrase);

        Console.WriteLine("Please enter 10 letters that you want revealed for: " + game.DisplayBlanks());
        var tenLetters = Console.ReadLine();
        var guess = tenLetters ?? "";

        var isValid = game.IsValid(guess);

        if(isValid){
            var result = game.Play(guess.ToCharArray());
            Console.WriteLine(result);
        } else {
            Console.WriteLine("You failed to enter 10 unique letters with no spaces.");
        }
        Console.WriteLine();
        Console.WriteLine();
        Console.WriteLine("================================");
        Console.WriteLine("========= GAME RESULTS =========");
        Console.WriteLine("================================");
        Console.WriteLine("The hidden phrase was: " + phrase);
    }
}
